name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r backend/requirements-test.txt

      - name: Rodar testes e cobertura
        run: |
          cd backend
          python -m pytest tests/ --cov=. --cov-report=term-missing --cov-report=html --cov-report=xml

      - name: Upload do relatório de cobertura HTML
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-backend-html
          path: backend/htmlcov/ 